### ISSUE TITLE
Top and bottom cut off on wide screen monitors

### ISSUE THREAD

**Issue by karmicthreat** [palanquin-software/tapeheads-issues#2]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/99cb5eef-313e-4d6a-9ae7-1880b79823e6">

Additionally 
<img width="127" alt="image" src="https://github.com/user-attachments/assets/c7b309e2-4ea8-4fa0-99e8-a93925e1eaa5">
Having two icons is super annoying.

**Comment by palanpanda** [comment]
@karmicthreat would you please provided your display resolution and dpi?
The icon problem is noted.

**Comment by karmicthreat** [comment]
Res in screenshot 1920x800
Monitor native res 3840x1600

**Comment by palanpanda** [comment]
@karmicthreat I noticed it's filling your screen horizontally, which suggests it's being treated as a HiDPI monitor. Is this a MacBook with the clamshell open, by any chance?

**Comment by karmicthreat** [comment]
No, its a mbp with the clamshell closed.

**Comment by palanpanda** [comment]
Hate to pester you about this ticket. This is the first bug I can't
replicate on one of my systems. Maybe it's time for me to buy a monitor
similar to yours, as a secondary.

1. What happens if you run in fullscreen mode?
2. What happens if you run it on the MBP screen?
3. Lastly, does it act any differently when the clamshell *is* open?

I will try not to bug you about it again, other than to say it is fixed.

**Comment by palanpanda** [comment]
Fixed in v0.6.3

The game window is now resizable and has a standard decorated window.

**Comment by karmicthreat** [comment]
I am just following up on this. I tried a few different resolutions in full-screen and windowed mode. The issue seems resolved.

**Comment by palanpanda** [comment]
@karmicthreat Super kind of you.
